name: GitHub Pages Deployment

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Handles overlapping deployments
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Checkout from repository
      - uses: actions/checkout@v4

      # Node setup
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      # NPM clean install
      - run: npm ci

      # NPM build for deployment
      - run: npm run build

      # Repo prep for GH pages deployment
      - uses: actions/configure-pages@v4

      # Upload build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # GH Pages deploymenyt
      - id: deployment
        uses: actions/deploy-pages@v4